import type { Metadata } from "next";

import "./globals.css";
import "../app/css/bootstrap.min.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "./css/style.css";
import AOSInitializer from "./AOSInitializer";

import { Kufam } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import logo from './Assests/logo4ina.png'
import Head from "next/head";


export const metadata: Metadata = {
  title: "4InA Technologie",
  description: "Generated by create next app",
};

const kufam = Kufam({
  subsets: ["latin"], 
  weight: ["400", "700"],
  
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr">
      
      <head>

                <link rel="icon" href="/logo4ina.png" />
       
                <script src="https://upload-widget.cloudinary.com/global/all.js"></script>

        <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />
        <link href="css/bootstrap.min.css" rel="stylesheet" />
        <link href="lib/animate/animate.min.css" rel="stylesheet" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        />
        <link href="css/style.css" rel="stylesheet" />
      
<script async src="https://www.googletagmanager.com/gtag/js?id=G-9QL8MY4WB9"></script>
<script>
{`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-9QL8MY4WB9');
          `}
</script>

<script>
  {`
  (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-TM4X5LFM');
  `}
</script>

      </head>
      <body className={kufam.className}>
      
  <AOSInitializer />
<noscript>
  {`
  <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TM4X5LFM"
height="0" width="0" style="display:none;visibility:hidden"></iframe>
  `}
</noscript>

      <script src="https://upload-widget.cloudinary.com/global/all.js"></script>

        <div className="page_container">
          <Navbar  />

          
          <main className="content-wrapper">{children}</main>
        </div>
          <Footer/>
      </body>
    </html>
  );
}
