import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "../app/css/bootstrap.min.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "./css/style.css";
import { Kufam } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

// Metadata configuration
export const metadata: Metadata = {
  title: "4InA Technologie",
  description: "Generated by create next app",
};

// Font configuration
const kufam = Kufam({
  subsets: ["latin"], 
  weight: ["400", "700"],
  // weight: "400", // Optional: Specify font weight if needed
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />
        <link href="css/bootstrap.min.css" rel="stylesheet" />
        <link href="lib/animate/animate.min.css" rel="stylesheet" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        />
        <link href="css/style.css" rel="stylesheet" />
      </head>
      <body className={kufam.className}>
        <div className="page-container">
          <Navbar />
          
          <main className="content-wrapper">{children}</main>
        </div>
          <Footer/>
      </body>
    </html>
  );
}
