import type { Metadata } from "next";

import "./globals.css";
import "../app/css/bootstrap.min.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "./css/style.css";
import AOSInitializer from "./AOSInitializer";

import { Poppins } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import logog from "../app/Assests/logo4ina.png"
import { Analytics } from "@vercel/analytics/next"
// export const metadata: Metadata = {
//   title: "4InA Technologie",
//   description: "Generated by create next app",
//   keywords: ["4ina", "4ina Technology", "Web Development", "Mobile App", "IoT", "AI", "Smart Solutions"],
//   authors: [{ name: "4ina Technology", url: "https://4inatechnology.com" }],
//   creator: "4ina Technology",
//   metadataBase: new URL("https://4inatechnology.com"),
//   openGraph: {
//     title: "4ina Technology | Innovate, Collaborate, Succeed",
//     description: "Explore our innovative web, mobile, AI, and IoT services tailored for the future.",
//     url: "https://4inatechnology.com",
//     siteName: "4ina Technology",
//     images: [
//       {
//         url: "../app/Assests/logo4ina.png",
//         width: 1200,
//         height: 630,
//         alt: "4ina Technology Website Preview",
//       },
//     ],
//     type: "website",
//   },
//   icons: {
//     icon: "/favicon.ico",
//   },
// };
export const metadata = {
  title: '4InA Technologie – AI-Powered Energy Monitoring & Predictive Maintenance',
  description: '4InA Technologie provides real-time energy monitoring and AI-driven predictive maintenance solutions for optimal energy efficiency.',
}
const poppins = Poppins({
  subsets: ["latin"], 
  weight: ["400", "700"],
  
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr">
      
      <head>
        {/* kk */}

        <meta name="google-site-verification" content="5qRlOQNaJ771i6hFI2xzZQ15dkBy2MUUDkqrzTzYq6A" />
        <meta name="robots" content="index, follow" />
        <meta name="author" content="4ina Technologie" />
        <meta name="keywords" content="Développement Web, Mobile, IoT, Analyse de données, IA, Tunisie" />

        {/* Données structurées JSON-LD */}
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "Organization",
          "name": "4ina Technologie",
          "url": "https://www.4inatechnologie.com",
          "logo": "https://www.4inatechnologie.com/favicon.ico",
          "contactPoint": {
            "@type": "ContactPoint",
            "telephone": "+216 XX XXX XXX",
            "contactType": "customer support",
            "areaServed": "TN"
          },
          "sameAs": [
            "https://www.linkedin.com/company/4ina-technologie",
            "https://www.facebook.com/4inatechnologie"
          ]
        }) }} />
        {/* kk */}
      <link rel="icon" href="/favicon.ico" type="image/x-icon" />
      <meta name="description" content="4InA Technologie provides real-time energy monitoring and AI-driven predictive maintenance solutions for optimal energy efficiency." />

                <script src="https://upload-widget.cloudinary.com/global/all.js"></script>
<script
  dangerouslySetInnerHTML={{
    __html: `
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','GTM-WXT2GD33');
    `,
  }}
></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />

        <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />
        <link href="css/bootstrap.min.css" rel="stylesheet" />
        <link href="lib/animate/animate.min.css" rel="stylesheet" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        />
        <link href="css/style.css" rel="stylesheet" />
      
<script async src="https://www.googletagmanager.com/gtag/js?id=G-9QL8MY4WB9"></script>
<script
  dangerouslySetInnerHTML={{
    __html: `
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-9QL8MY4WB9');
    `,
  }}
></script>





      </head>
      <body className={poppins.className}>
      
  <AOSInitializer />
 <noscript>
  {`
  <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WXT2GD33"
height="0" width="0" style="display:none;visibility:hidden"></iframe>
  `}
</noscript> 


    

        <div className="page_container">
          <Navbar  />

          
          <main className="content-wrapper">{children}
 <Analytics />

          </main>
        </div>
          <Footer/>
      </body>
    </html>
  );
}
